#!/usr/bin/env bash
# FizBuzz math game in shell script! Print numbers between 1-100.
#	If disible by 3, print Fizz
#	If disible by 5, print Buzz
#	If disible by 15, print FizzBuzz
for num in {1..100}
do

	if [[ $((num%15)) = 0 ]];
	then
		echo FizzBuzz
	elif [[ $((num%5)) = 0 ]];
	then
		echo Buzz
	elif [[ $((num%3)) = 0 ]];
	then
		echo Fizz
	else
		echo $num
	fi
done

