#!/usr/bin/env bash
# Loop through 10 times and print 'Best School' on the 9th loop, print 'Hi' then 'Best School', While loop + if statement
i=1
while ((i<=10))
do

	if [ $i -eq "10" ];
	then
		echo Hi
	fi

	echo Best School
        ((i+=1))
done
