#!/usr/bin/env bash
# Print 'Best School', except for: bad luck after #4 and good luck after #8
i=1
while ((i<=10))
do
	if [ $i -eq '4' ];
	then
		echo bad luck
	elif [ $i -eq '8' ];
	then
		echo good luck
	else
		echo Best School
	fi
	((i+=1))
done
