#!/usr/bin/env bash
# Print numbers 1-20, with special cases at 4,9,17 (print number, then special case)
i=1
while ((i<=20))
do
	echo $i
	case $i in
		'4')
			echo bad luck from China;;
		'9')
			echo bad luck from Japan;;
		'17')
			echo bad luck from Italy;;
	esac
	((i+=1))
done
