#!/usr/bin/env bash
#Print minutes 1-59 for hours 0-12
hour=0
minute=1

while ((hour<=12))
do
	echo Hour: $hour
	minute=1
	while ((minute<60))
	do
		echo $minute
		((minute+=1))
	done
	((hour+=1))
done
